services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///database.db
      - WHATSAPP_API_URL=http://waha:3000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - waha
    networks:
      - app-network

  waha:
    build:
      context: .
      dockerfile: Dockerfile.waha
    container_name: waha
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.sessions:/app/.sessions
    environment:
      - WAHA_PRINT_QR=true
      - WAHA_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_HOOK_URL=http://web:5000/whatsapp/webhook
      - WHATSAPP_HOOK_EVENTS=poll.vote,poll.vote.failed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
